// Global using directives

global using CqlTranslationDictionary = System.Collections.Immutable.ImmutableDictionary<CqlSdkPrototype.ElmVersionedLibraryIdentifier, CqlSdkPrototype.CqlToElm.CqlTranslation.CqlTranslationEntry>;
global using ElmCompilationDictionary = System.Collections.Immutable.ImmutableDictionary<CqlSdkPrototype.ElmVersionedLibraryIdentifier, CqlSdkPrototype.ElmToAssembly.ElmCompilation.ElmCompilationEntry>;