using System.CodeDom.Compiler;
using System.Reflection;
using Hl7.Cql.Abstractions;
using Microsoft.Extensions.Logging;

namespace CqlSdkPrototype.Runtime;

public readonly record struct CqlRuntimeLibrary
{
    private CqlRuntimeLibrary(
        Type libraryType,
        string cqlToolVersion,
        CqlVersionedLibraryIdentifier versionedIdentifier)
    {
        LibraryType = libraryType;
        CqlToolVersion = cqlToolVersion;
        VersionedIdentifier = versionedIdentifier;
    }

    public bool IsDefault() => LibraryType is null; // Quick check for default value

    public static CqlRuntimeLibrary CreateFromType(
        Type libraryType,
        ILogger? logger = null)
    {
        if (!TryCreateFromType(libraryType, out var cqlRuntimeLibrary, logger))
            throw new InvalidOperationException($"Type {libraryType.FullName} is not a CQL library type.");

        return cqlRuntimeLibrary;
    }

    public static bool TryCreateFromType(
        Type libraryType,
        out CqlRuntimeLibrary cqlRuntimeLibrary,
        ILogger? logger = null)
    {
        cqlRuntimeLibrary = default;

        var cqlLibraryAttribute = libraryType.GetCustomAttributes<CqlLibraryAttribute>().FirstOrDefault();
        if (cqlLibraryAttribute is null)
        {
            logger?.LogDebug(
                "Type {type} is not a CQL library because it does not have a CqlLibraryAttribute.",
                libraryType.FullName); return false;
        }

        var generatedCodeAttribute = libraryType.GetCustomAttributes<GeneratedCodeAttribute>().FirstOrDefault();
        var cqlTool = generatedCodeAttribute?.Tool;
        var cqlToolVersion = generatedCodeAttribute?.Version;
        if (cqlTool != ".NET Code Generation" || cqlToolVersion is null)
        {
            logger?.LogDebug(
                "Skipping type {type} because it was not generated by the CQL tool .NET Code Generation",
                libraryType.FullName);
            return false;
        }

        var cqlLibraryIdentifier = CqlLibraryIdentifier.Parse(cqlLibraryAttribute.Identifier);
        var cqlLibraryVersion = CqlLibraryVersion.ParseOrEmpty(cqlLibraryAttribute.Version);
        var cqlLibraryVersionedIdentifier = CqlVersionedLibraryIdentifier.FromNameAndVersion(cqlLibraryIdentifier, cqlLibraryVersion);

        logger?.LogDebug(
            "Found CQL library type {type} with versioned identifier {vid}, generated with tool version {toolVersion}.",
            libraryType.FullName,
            cqlLibraryVersionedIdentifier,
            cqlToolVersion);

        cqlRuntimeLibrary = new CqlRuntimeLibrary(
            libraryType,
            cqlToolVersion,
            cqlLibraryVersionedIdentifier);
        return true;
    }

    public Type LibraryType { get; init; }
    public string CqlToolVersion { get; }
    public CqlVersionedLibraryIdentifier VersionedIdentifier { get; init; }

    public void Deconstruct(
        out Type libraryType,
        out string cqlToolVersion,
        out CqlVersionedLibraryIdentifier versionedIdentifier)
    {
        libraryType = LibraryType;
        cqlToolVersion = CqlToolVersion;
        versionedIdentifier = VersionedIdentifier;
    }
}