using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using Hl7.Cql.Abstractions;
using Microsoft.Extensions.Logging;

namespace CqlSdkPrototype.Runtime;

internal readonly record struct CqlRuntimeLibrary
{
    private CqlRuntimeLibrary(
        object libraryInstanceOrType,
        string cqlToolVersion,
        CqlVersionedLibraryIdentifier versionedIdentifier)
    {
        Debug.Assert(libraryInstanceOrType is Type || libraryInstanceOrType?.GetType().BaseType == typeof(object));
        LibraryInstanceOrType = libraryInstanceOrType;
        CqlToolVersion = cqlToolVersion;
        VersionedIdentifier = versionedIdentifier;
    }

    public bool IsDefault() => LibraryInstanceOrType is null; // Quick check for default value

    public static CqlRuntimeLibrary CreateFromType(
        Type libraryType,
        ILogger? logger = null)
    {
        if (!TryCreateFromType(libraryType, out var cqlRuntimeLibrary, logger))
            throw new InvalidOperationException($"Type {libraryType.FullName} is not a CQL library type.");

        return cqlRuntimeLibrary;
    }

    public static bool TryCreateFromType(
        Type libraryType,
        out CqlRuntimeLibrary cqlRuntimeLibrary,
        ILogger? logger = null)
    {
        cqlRuntimeLibrary = default;

        var cqlLibraryAttribute = libraryType.GetCustomAttributes<CqlLibraryAttribute>().FirstOrDefault();
        if (cqlLibraryAttribute is null)
        {
            logger?.LogDebug(
                "Type {type} is not a CQL library because it does not have a CqlLibraryAttribute.",
                libraryType.FullName); return false;
        }

        var generatedCodeAttribute = libraryType.GetCustomAttributes<GeneratedCodeAttribute>().FirstOrDefault();
        var cqlTool = generatedCodeAttribute?.Tool;
        var cqlToolVersion = generatedCodeAttribute?.Version;
        if (cqlTool != ".NET Code Generation" || cqlToolVersion is null)
        {
            logger?.LogDebug(
                "Skipping type {type} because it was not generated by the CQL tool .NET Code Generation",
                libraryType.FullName);
            return false;
        }

        var cqlLibraryIdentifier = CqlLibraryIdentifier.Parse(cqlLibraryAttribute.Identifier);
        var cqlLibraryVersion = CqlLibraryVersion.ParseOrEmpty(cqlLibraryAttribute.Version);
        var cqlLibraryVersionedIdentifier = CqlVersionedLibraryIdentifier.FromNameAndVersion(cqlLibraryIdentifier, cqlLibraryVersion);

        // VERSIONING: Depending on the tool version, the way the library is generated may differ.
        Debug.Assert(cqlToolVersion == "2.0.8.0");
        var cqlLibraryTypeOrInstance =
            libraryType.GetProperty("Instance", BindingFlags.Public | BindingFlags.Static)?.GetValue(null)
            ?? throw new InvalidOperationException($"Unable to create an instance of {libraryType.FullName}");

        logger?.LogDebug(
            "Found CQL library type {type} with versioned identifier {vid}, generated with tool version {toolVersion}.",
            libraryType.FullName,
            cqlLibraryVersionedIdentifier,
            cqlToolVersion);

        cqlRuntimeLibrary = new CqlRuntimeLibrary(
            cqlLibraryTypeOrInstance,
            cqlToolVersion,
            cqlLibraryVersionedIdentifier);
        return true;
    }

    private object LibraryInstanceOrType { get; }
    public string CqlToolVersion { get; }
    public CqlVersionedLibraryIdentifier VersionedIdentifier { get; }

    internal Type GetLibraryType() => LibraryInstanceOrType switch
    {
        Type type => type,
        object instance => instance.GetType(),
        _ when IsDefault() => throw new InvalidOperationException("Cannot use members on default instance."),
        _ => throw new UnreachableException()
    };

    public void Deconstruct(
        out string cqlToolVersion,
        out CqlVersionedLibraryIdentifier versionedIdentifier)
    {
        cqlToolVersion = CqlToolVersion;
        versionedIdentifier = VersionedIdentifier;
    }
}