using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using Hl7.Cql.Abstractions;
using Microsoft.Extensions.Logging;

namespace CqlSdkPrototype.Runtime;


/// <summary>
/// Represents an invoker for a CQL library.
/// </summary>
public abstract partial class LibraryInvoker
{
    public abstract CqlVersionedLibraryIdentifier LibraryVersionedIdentifier { get; }

    public abstract IReadOnlyDictionary<string, LibraryDeclarationInvoker> Declarations { get; }
}

partial class LibraryInvoker
{
    public static bool TryCreateFromType(
        Type libraryType,
        [NotNullWhen(true)] out LibraryInvoker? libraryInvoker,
        ILogger? logger = null)
    {
        libraryInvoker = null;

        if (libraryType.GetCustomAttribute<CqlLibraryAttribute>() is not {})
        {
            logger?.LogDebug(
                "Type {type} is not a CQL library because it does not have a CqlLibraryAttribute.",
                libraryType.FullName);
            return false;
        }

        if (
            libraryType.GetCustomAttribute<GeneratedCodeAttribute>() is not
                {
                    Tool: ".NET Code Generation",
                    Version:{} version
                }
            || !Version.TryParse(version, out var cqlToolVersion))
        {
            logger?.LogDebug(
                "Skipping type {type} because it was not generated by the CQL tool .NET Code Generation",
                libraryType.FullName);
            return false;
        }

        if (cqlToolVersion >= new Version(2, 0, 8, 0)
            && cqlToolVersion < new Version(2, 1))
        {
            return TryCreateFromType_2_0_8_0(libraryType, out libraryInvoker, logger);
        }

        logger?.LogDebug(
            "Skipping type {type} because it was generated with an unsupported version {ver} of the CQL tool.",
            libraryType.FullName,
            cqlToolVersion);
        return false;

    }

    private static bool TryCreateFromType_2_0_8_0(
        Type libraryType,
        [NotNullWhen(true)] out LibraryInvoker? libraryInvoker,
        ILogger? logger = null)
    {
        libraryInvoker = null;
        if (GetLibraryFromStaticInstanceProperty(libraryType) is not ILibrary asILibrary)
        {
            logger?.LogDebug(
                "Skipping type {type} because it does not implement ILibrary.",
                libraryType.FullName);
            return false;
        }

        libraryInvoker = new LibraryInvoker_2_0_8_0(asILibrary);
        return true;
    }

    private static object GetLibraryFromStaticInstanceProperty(Type libraryType)
    {
        return libraryType.GetProperty("Instance", BindingFlags.Public | BindingFlags.Static)?.GetValue(null)
               ?? throw new InvalidOperationException($"Unable to create an instance of {libraryType.FullName}");
    }
}