using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using Hl7.Cql.Abstractions;
using Hl7.Cql.Runtime.Hosting;
using Microsoft.Extensions.Logging;

namespace CqlSdkPrototype.Runtime;


/// <summary>
/// Represents an invoker for a CQL library.
/// </summary>
public abstract class LibraryInvoker
{
    public abstract CqlVersionedLibraryIdentifier LibraryVersionedIdentifier { get; }

    public abstract IReadOnlyDictionary<string, LibraryDefinitionInvoker> Definitions { get; }

    public static bool TryCreateFromType(
        CqlRuntimeApi cqlRuntimeApi,
        Type libraryType,
        [NotNullWhen(true)] out LibraryInvoker? libraryInvoker)
    {
        var logger = cqlRuntimeApi.Options.ServiceProvider.GetLogger<LibraryInvoker>();
        libraryInvoker = null;
        if (libraryType.GetCustomAttribute<CqlLibraryAttribute>() is not {})
        {
            logger?.LogDebug(
                "Type {type} is not a CQL library because it does not have a CqlLibraryAttribute.",
                libraryType.FullName);
            return false;
        }

        // The current version is set in by 'VersionPrefix' in 'cql-sdk.props',
        // which is also used to generate the 'CqlLibraryAttribute' in the CQL library.
        if (libraryType.GetCustomAttribute<GeneratedCodeAttribute>() is not
            {
                Tool: ".NET Code Generation",
                Version:{} version
            }
            || !Version.TryParse(version, out var cqlToolVersion))
        {
            logger?.LogDebug(
                "Skipping type {type} because it was not generated by the CQL tool .NET Code Generation",
                libraryType.FullName);
            return false;
        }

        if (LibraryInvoker_2_0_8_0.SupportsVersion(cqlToolVersion))
        {
            return LibraryInvoker_2_0_8_0.TryCreateFromType(cqlRuntimeApi, libraryType, out libraryInvoker);
        }

        logger?.LogDebug(
            "Skipping type {type} because it was generated with an unsupported version {ver} of the CQL tool.",
            libraryType.FullName,
            cqlToolVersion);
        return false;
    }
}