@echo off
SETLOCAL EnableDelayedExpansion

xsd /c .\library.xsd .\types.xsd .\clinicalexpression.xsd .\cqlannotations.xsd .\expression.xsd /o:.. /n:Hl7.Cql.Elm

PUSHD ..

REM Post processing expression.cs, into temp.txt, then replacing that into Elm.cs
SET in_file=expression.cs
SET out_file=Elm.cs
SET temp_file=temp.txt
SET line_number=0

REM Clear the temporary file if it exists
IF EXIST %temp_file% (
    DEL %temp_file%
)

REM Read each line from the existing file
FOR /F "tokens=* delims=" %%A IN (%in_file%) DO (
    SET /A line_number+=1
    IF !line_number! EQU 11 (
        REM Replace line 11
        ECHO // This source code was auto-generated by 'Generate Classes.cmd'
        ECHO.
        ECHO #nullable enable
        ECHO #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        ECHO.
    ) ELSE IF !line_number! EQU 12 (
        REM Remove line 12
    ) ELSE (
        REM Copy line
        ECHO.%%A
    )
) >> %temp_file%

REM Move the temporary file to the output file
MOVE /Y %temp_file% %out_file%
DEL %in_file%

POPD
ENDLOCAL