using System;
using System.Collections.Generic;
using System.Text;

namespace Ncqa.Cql.Runtime
{
    public enum CqlOperator
    {
        And,
        Or,
        Xor,
        /// <summary>
        /// ConvertQuantity(Quantity, string units);
        /// </summary>
        ConvertQuantity,
        /// <summary>
        /// Select(IEnumerable, Lambda);
        /// </summary>
        Select,
        /// <summary>
        /// Convert(Type current, Type desired)
        /// </summary>
        Convert,
        Coalesce,
        IsFalse,
        IsTrue,
        ListEqual,
        EnumEqualsString,
        Equal,
        Equivalent,
        ListEquivalent,
        Greater,
        GreaterOrEqual,
        Less,
        LessOrEqual,
        Negate,
        Abs,
        Add,
        Ceiling,
        Divide,
        Floor,
        Exp,
        HighBoundary,
        Log,
        LowBoundary,
        Ln,
        Modulo,
        Multiply,
        Not,
        Precision,
        Predecessor,
        Pow,
        /// <summary>
        /// Round(value, string precision)
        /// </summary>
        Round,
        Subtract,
        Successor,
        Truncate,
        TruncatedDivide,
        Concatenate,
        /// <summary>
        /// Combine(string source, string? separator)
        /// </summary>
        Combine,
        EndsWith,
        CharAt,
        ElementAt,
        LastPositionOf,
        ListLength,
        StringLength,
        Lower,
        Matches,
        PositionOf,
        ReplaceMatches,
        Split,
        StartsWith,
        Substring,
        Upper,
        IntervalAfterInterval,
        IntervalAfterElement,
        ElementAfterInterval,
        After,
        IntervalBeforeInterval,
        IntervalBeforeElement,
        ElementBeforeInterval,
        Before,
        Date,
        DateTime,
        DateComponent,
        TimeComponent,
        TimeZoneComponent,
        DateTimeComponent,
        DifferenceBetween,
        DurationBetween,
        Now,
        IntervalSameAs,
        SameAs,
        IntervalSameOrAfter,
        SameOrAfter,
        IntervalSameOrBefore,
        SameOrBefore,
        Time,
        TimeOfDay,
        Today,
        Collapse,
        ListContains,
        IntervalContains,
        IntervalEnd,
        Ends,
        ListExcept,
        IntervalExcept,
        Expand,
        InList,
        InInterval,
        ListIncludesList,
        ListIncludesElement,
        IntervalIncludesInterval,
        IntervalIncludesElement,
        ListIntersect,
        IntervalIntersect,
        Meets,
        Overlaps,
        PointFrom,
        IntervalProperlyIncludesInterval,
        ListProperlyIncludesList,
        ListProperlyIncludesElement,
        IntervalProperlyIncludesElement,
        IntervalStart,
        Starts,
        ListUnion,
        IntervalUnion,
        Width,
        Distinct,
        Exists,
        Flatten,
        IndexOf,
        First,
        Last,
        Tail,
        AllTrue,
        AnyTrue,
        Avg,
        Count,
        GeometricMean,
        MaxElementInList,
        MinElementInList,
        Median,
        Mode,
        PopulationStdDev,
        PopulationVariance,
        StdDev,
        Sum,
        Product,
        Variance,
        Slice,
        CalculateAge,
        CalculateAgeAt,
        CodeInValueSet,
        ConceptInValueSet,
        StringInValueSet,
        Message,
        ConvertsToInteger,
        ConvertsToLong,
        ConvertsToDecimal,
        ConvertsToDateTime,
        ConvertsToDate,
        ConvertsToTime,
        ConvertsToString,
        ConvertsToQuantity,
        Descendents,
        SelectMany,
        SelectManyResults,
        Where,
        Sort,
        SortBy,
        Single,
        MeetsAfter,
        MeetsBefore,
        Ratio,
        OverlapsBefore,
        OverlapsAfter,
        ToList,
        CodesInValueSet,
        ConceptsInValueSet,
        StringsInValueSet,
        Quantity,
        Interval,
        Retrieve,
        LateBoundProperty,
        PropertyOrDefault,
        MinimumValue,
        MaximumValue,
        ResolveValueSet
    }
}
