//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from cql.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Hl7.Cql.CqlToElm.Grammar.r2 {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="cqlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IcqlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.modelDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelDefinitions([NotNull] cqlParser.ModelDefinitionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.modelDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelDefinitions([NotNull] cqlParser.ModelDefinitionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModel([NotNull] cqlParser.ModelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModel([NotNull] cqlParser.ModelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.modelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelDefinition([NotNull] cqlParser.ModelDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.modelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelDefinition([NotNull] cqlParser.ModelDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.modelUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModelUri([NotNull] cqlParser.ModelUriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.modelUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModelUri([NotNull] cqlParser.ModelUriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDefinition([NotNull] cqlParser.TypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDefinition([NotNull] cqlParser.TypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.literalTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralTypeDefinition([NotNull] cqlParser.LiteralTypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.literalTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralTypeDefinition([NotNull] cqlParser.LiteralTypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.classTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassTypeDefinition([NotNull] cqlParser.ClassTypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.classTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassTypeDefinition([NotNull] cqlParser.ClassTypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.classElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassElements([NotNull] cqlParser.ClassElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.classElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassElements([NotNull] cqlParser.ClassElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.classElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassElement([NotNull] cqlParser.ClassElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.classElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassElement([NotNull] cqlParser.ClassElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseType([NotNull] cqlParser.BaseTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseType([NotNull] cqlParser.BaseTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseTypeSpecifier([NotNull] cqlParser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseTypeSpecifier([NotNull] cqlParser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.genericTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypeDefinition([NotNull] cqlParser.GenericTypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.genericTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypeDefinition([NotNull] cqlParser.GenericTypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.genericArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericArguments([NotNull] cqlParser.GenericArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.genericArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericArguments([NotNull] cqlParser.GenericArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.genericTypeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypeConstraint([NotNull] cqlParser.GenericTypeConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.genericTypeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypeConstraint([NotNull] cqlParser.GenericTypeConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.libraryDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibraryDefinitions([NotNull] cqlParser.LibraryDefinitionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.libraryDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibraryDefinitions([NotNull] cqlParser.LibraryDefinitionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.library"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibrary([NotNull] cqlParser.LibraryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.library"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibrary([NotNull] cqlParser.LibraryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.libraryDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibraryDefinition([NotNull] cqlParser.LibraryDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.libraryDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibraryDefinition([NotNull] cqlParser.LibraryDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.usingDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingDefinition([NotNull] cqlParser.UsingDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.usingDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingDefinition([NotNull] cqlParser.UsingDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.includeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeDefinition([NotNull] cqlParser.IncludeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.includeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeDefinition([NotNull] cqlParser.IncludeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.localIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalIdentifier([NotNull] cqlParser.LocalIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.localIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalIdentifier([NotNull] cqlParser.LocalIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessModifier([NotNull] cqlParser.AccessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessModifier([NotNull] cqlParser.AccessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.parameterDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDefinition([NotNull] cqlParser.ParameterDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.parameterDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDefinition([NotNull] cqlParser.ParameterDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codesystemDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodesystemDefinition([NotNull] cqlParser.CodesystemDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codesystemDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodesystemDefinition([NotNull] cqlParser.CodesystemDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.valuesetDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValuesetDefinition([NotNull] cqlParser.ValuesetDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.valuesetDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValuesetDefinition([NotNull] cqlParser.ValuesetDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codesystems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodesystems([NotNull] cqlParser.CodesystemsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codesystems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodesystems([NotNull] cqlParser.CodesystemsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codesystemIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodesystemIdentifier([NotNull] cqlParser.CodesystemIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codesystemIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodesystemIdentifier([NotNull] cqlParser.CodesystemIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.libraryIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLibraryIdentifier([NotNull] cqlParser.LibraryIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.libraryIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLibraryIdentifier([NotNull] cqlParser.LibraryIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeDefinition([NotNull] cqlParser.CodeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeDefinition([NotNull] cqlParser.CodeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.conceptDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConceptDefinition([NotNull] cqlParser.ConceptDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.conceptDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConceptDefinition([NotNull] cqlParser.ConceptDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdentifier([NotNull] cqlParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdentifier([NotNull] cqlParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] cqlParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] cqlParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.keywordIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeywordIdentifier([NotNull] cqlParser.KeywordIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.keywordIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeywordIdentifier([NotNull] cqlParser.KeywordIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeIdentifier([NotNull] cqlParser.CodeIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeIdentifier([NotNull] cqlParser.CodeIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codesystemId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodesystemId([NotNull] cqlParser.CodesystemIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codesystemId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodesystemId([NotNull] cqlParser.CodesystemIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.valuesetId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValuesetId([NotNull] cqlParser.ValuesetIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.valuesetId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValuesetId([NotNull] cqlParser.ValuesetIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.versionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersionSpecifier([NotNull] cqlParser.VersionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.versionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersionSpecifier([NotNull] cqlParser.VersionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.codeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeId([NotNull] cqlParser.CodeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.codeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeId([NotNull] cqlParser.CodeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.displayClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplayClause([NotNull] cqlParser.DisplayClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.displayClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplayClause([NotNull] cqlParser.DisplayClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] cqlParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] cqlParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.choiceTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChoiceTypeSpecifier([NotNull] cqlParser.ChoiceTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.choiceTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChoiceTypeSpecifier([NotNull] cqlParser.ChoiceTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.tupleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleTypeSpecifier([NotNull] cqlParser.TupleTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.tupleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleTypeSpecifier([NotNull] cqlParser.TupleTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.tupleElementDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleElementDefinition([NotNull] cqlParser.TupleElementDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.tupleElementDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleElementDefinition([NotNull] cqlParser.TupleElementDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.namedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedTypeSpecifier([NotNull] cqlParser.NamedTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.namedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedTypeSpecifier([NotNull] cqlParser.NamedTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.genericTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypeSpecifier([NotNull] cqlParser.GenericTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.genericTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypeSpecifier([NotNull] cqlParser.GenericTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryExpression([NotNull] cqlParser.BinaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryExpression([NotNull] cqlParser.BinaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parentheticalExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParentheticalExpression([NotNull] cqlParser.ParentheticalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parentheticalExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParentheticalExpression([NotNull] cqlParser.ParentheticalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierExpression([NotNull] cqlParser.IdentifierExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExpression([NotNull] cqlParser.IdentifierExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>functionInvocationExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionInvocationExpression([NotNull] cqlParser.FunctionInvocationExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>functionInvocationExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionInvocationExpression([NotNull] cqlParser.FunctionInvocationExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpression([NotNull] cqlParser.LiteralExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpression([NotNull] cqlParser.LiteralExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.functionInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionInvocation([NotNull] cqlParser.FunctionInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.functionInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionInvocation([NotNull] cqlParser.FunctionInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.returnClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnClause([NotNull] cqlParser.ReturnClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.returnClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnClause([NotNull] cqlParser.ReturnClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.binaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOperator([NotNull] cqlParser.BinaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.binaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOperator([NotNull] cqlParser.BinaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] cqlParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] cqlParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantity([NotNull] cqlParser.QuantityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantity([NotNull] cqlParser.QuantityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.quantityValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantityValue([NotNull] cqlParser.QuantityValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.quantityValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantityValue([NotNull] cqlParser.QuantityValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="cqlParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnit([NotNull] cqlParser.UnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="cqlParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnit([NotNull] cqlParser.UnitContext context);
}
} // namespace Hl7.Cql.CqlToElm.Grammar.r2
