//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from cql.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Hl7.Cql.CqlToElm.Grammar.r2 {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="cqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IcqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.modelDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelDefinitions([NotNull] cqlParser.ModelDefinitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel([NotNull] cqlParser.ModelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.modelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelDefinition([NotNull] cqlParser.ModelDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.modelUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModelUri([NotNull] cqlParser.ModelUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDefinition([NotNull] cqlParser.TypeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.literalTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralTypeDefinition([NotNull] cqlParser.LiteralTypeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.classTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassTypeDefinition([NotNull] cqlParser.ClassTypeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.classElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassElements([NotNull] cqlParser.ClassElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.classElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassElement([NotNull] cqlParser.ClassElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseType([NotNull] cqlParser.BaseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseTypeSpecifier([NotNull] cqlParser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.genericTypeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypeDefinition([NotNull] cqlParser.GenericTypeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.genericArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericArguments([NotNull] cqlParser.GenericArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.genericTypeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypeConstraint([NotNull] cqlParser.GenericTypeConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.libraryDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibraryDefinitions([NotNull] cqlParser.LibraryDefinitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.library"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary([NotNull] cqlParser.LibraryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.libraryDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibraryDefinition([NotNull] cqlParser.LibraryDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.usingDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDefinition([NotNull] cqlParser.UsingDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.includeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeDefinition([NotNull] cqlParser.IncludeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.localIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalIdentifier([NotNull] cqlParser.LocalIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessModifier([NotNull] cqlParser.AccessModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.parameterDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDefinition([NotNull] cqlParser.ParameterDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codesystemDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodesystemDefinition([NotNull] cqlParser.CodesystemDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.valuesetDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValuesetDefinition([NotNull] cqlParser.ValuesetDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codesystems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodesystems([NotNull] cqlParser.CodesystemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codesystemIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodesystemIdentifier([NotNull] cqlParser.CodesystemIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.libraryIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibraryIdentifier([NotNull] cqlParser.LibraryIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeDefinition([NotNull] cqlParser.CodeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.conceptDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConceptDefinition([NotNull] cqlParser.ConceptDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdentifier([NotNull] cqlParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] cqlParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.keywordIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeywordIdentifier([NotNull] cqlParser.KeywordIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeIdentifier([NotNull] cqlParser.CodeIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codesystemId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodesystemId([NotNull] cqlParser.CodesystemIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.valuesetId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValuesetId([NotNull] cqlParser.ValuesetIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.versionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersionSpecifier([NotNull] cqlParser.VersionSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.codeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeId([NotNull] cqlParser.CodeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.displayClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplayClause([NotNull] cqlParser.DisplayClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] cqlParser.TypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.choiceTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoiceTypeSpecifier([NotNull] cqlParser.ChoiceTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.tupleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleTypeSpecifier([NotNull] cqlParser.TupleTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.tupleElementDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleElementDefinition([NotNull] cqlParser.TupleElementDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.namedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedTypeSpecifier([NotNull] cqlParser.NamedTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.genericTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericTypeSpecifier([NotNull] cqlParser.GenericTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExpression([NotNull] cqlParser.BinaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parentheticalExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentheticalExpression([NotNull] cqlParser.ParentheticalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierExpression([NotNull] cqlParser.IdentifierExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionInvocationExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionInvocationExpression([NotNull] cqlParser.FunctionInvocationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="cqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] cqlParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.functionInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionInvocation([NotNull] cqlParser.FunctionInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.returnClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnClause([NotNull] cqlParser.ReturnClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.binaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOperator([NotNull] cqlParser.BinaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] cqlParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantity([NotNull] cqlParser.QuantityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.quantityValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantityValue([NotNull] cqlParser.QuantityValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="cqlParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnit([NotNull] cqlParser.UnitContext context);
}
} // namespace Hl7.Cql.CqlToElm.Grammar.r2
