@echo off
SETLOCAL EnableDelayedExpansion

REM ============================================================================
REM Elm.g.cs Generator (Version 2 - Using xsd2cs tool)
REM ============================================================================
REM This script uses the new xsd2cs tool to generate C# classes from XSD files.
REM It replaces the direct xsd.exe call with a wrapped version that provides
REM better tooling support and prepares for future enhancements.
REM
REM NOTE: This is a testing/validation version. After verification that the
REM output matches the original, this can replace Elm.g.cs-Generate.cmd.
REM ============================================================================

REM Note: Generated C# files must have file extension of .g.cs
REM For more info regarding nullability on generated files, see: https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references

SET in_file=Elm.g.cs
SET temp_file=Elm.g.cs.tmp
SET out_file=Elm.g.cs
SET tool_path=..\..\tools\XsdToCSharpConverter\bin\Debug\net8.0\xsd2cs.dll

ECHO Checking for XSD to C# converter tool...
IF NOT EXIST "%tool_path%" (
    ECHO Tool not found. Building XSD to C# converter...
    PUSHD ..\..\tools\XsdToCSharpConverter
    dotnet build
    IF ERRORLEVEL 1 (
        POPD
        ECHO Error: Failed to build xsd2cs tool
        EXIT /B 1
    )
    POPD
)

PUSHD Schema

ECHO Generating C# from XSD files using xsd2cs tool...
dotnet "%tool_path%" /c .\library.xsd .\clinicalexpression.xsd .\cqlannotations.xsd .\expression.xsd /o:.. /n:Hl7.Cql.Elm /out:Elm.g.cs /q

IF ERRORLEVEL 1 (
    POPD
    ECHO Error: Failed to generate C# code from XSD files
    EXIT /B 1
)

POPD

REM Post-process the generated file
ECHO Post-processing generated file: '%in_file%' -^> '%out_file%'

IF EXIST %temp_file% (
    DEL %temp_file%
)

REM Read each line from the existing file
SET line_number=0

FOR /F "tokens=* delims=" %%A IN (%in_file%) DO (
    SET /A line_number+=1
    IF !line_number! EQU 11 (
        REM Replace line 11
        ECHO // This source code was auto-generated by 'Elm.g.cs-Generate.cmd'
    ) ELSE IF !line_number! EQU 13 (
        REM Insert after line 13 (which is now line 12 due to the replacement above)
        ECHO #pragma warning disable CS1591 // Missing XML comment for publicly visible constructors
        ECHO // #pragma warning disable RS0016 // Symbol not declared as part of the public spec
        ECHO.
        ECHO.%%A
    ) ELSE (
        REM Copy line
        ECHO.%%A
    )
) >> %temp_file%

REM Move the temporary file to the output file
ECHO Moving '%temp_file%' to '%out_file%'
MOVE /Y %temp_file% %out_file% > NUL

REM Cleanup
ECHO Removing intermediate file '%in_file%'
DEL %in_file%

ECHO.
ECHO Successfully generated %out_file%
ECHO.
ECHO To verify: Compare this output with the version generated by Elm.g.cs-Generate.cmd
ECHO They should be byte-for-byte identical.

ENDLOCAL
