@echo off
SETLOCAL EnableDelayedExpansion

REM Note on : REM Generated C# files must have file extension of .g.cs
REM For more info regarding nullability on generated files, see: https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references
SET in_file=expression.cs
SET temp_file=Elm.g.cs.tmp
SET out_file=Elm.g.cs

PUSHD Schema

ECHO Generating xsd into C#: '%in_file%'
xsd /c .\library.xsd .\clinicalexpression.xsd .\cqlannotations.xsd .\expression.xsd /o:.. /n:Hl7.Cql.Elm > NUL
POPD


REM Clear the temporary file if it exists
ECHO Post processing into temporary file: '%temp_file%'

IF EXIST %temp_file% (
    DEL %temp_file%
)

REM Read each line from the existing file
SET line_number=0

FOR /F "tokens=* delims=" %%A IN (%in_file%) DO (
    SET /A line_number+=1
    IF !line_number! EQU 11 (
        REM Replace line 11
        ECHO // This source code was auto-generated by 'Elm.g.cs-Generate.cmd'
    ) ELSE IF !line_number! EQU 13 (
        REM Insert
        ECHO #pragma warning disable CS1591 // Missing XML comment for publicly visible constructors
        ECHO // #pragma warning disable RS0016 // Symbol not declared as part of the public spec
        ECHO.
        ECHO.%%A
    ) ELSE (
        REM Copy line
        ECHO.%%A
    )
) >> %temp_file%

REM Move the temporary file to the output file
ECHO Replacing '%temp_file%' over 'out_file%'

MOVE /Y %temp_file% %out_file% > NUL

REM Cleanup
ECHO Removing '%in_file%'
DEL %in_file%

ENDLOCAL