@echo off
SETLOCAL EnableDelayedExpansion

SET in_file=expression.cs
SET out_file=Elm.cs
SET temp_file=temp.txt
SET line_number=0

PUSHD Schema
ECHO Generating xsd into C#: '%in_file%'
xsd /c .\library.xsd .\types.xsd .\clinicalexpression.xsd .\cqlannotations.xsd .\expression.xsd /o:.. /n:Hl7.Cql.Elm > NUL
POPD


REM Clear the temporary file if it exists
ECHO Post processing into temporary file: '%temp_file%'
IF EXIST %temp_file% (
    DEL %temp_file%
)

REM Read each line from the existing file
FOR /F "tokens=* delims=" %%A IN (%in_file%) DO (
    SET /A line_number+=1
    IF !line_number! EQU 1 (
        ECHO #nullable enable
        ECHO #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        ECHO.
    ) ELSE IF !line_number! EQU 11 (
        REM Replace line 11
        ECHO // This source code was auto-generated by 'Generate Elm.cs from Schema.cmd'
    ) ELSE (
        REM Copy line
        ECHO.%%A
    )
) >> %temp_file%

REM Move the temporary file to the output file
ECHO Replacing '%temp_file%' over 'out_file%'
MOVE /Y %temp_file% %out_file% > NUL

ECHO Removing '%in_file%'
DEL %in_file%

ENDLOCAL