using System.Diagnostics;
using Hl7.Cql.Fhir;
using Hl7.Cql.Primitives;
using Hl7.Cql.Runtime;
using Hl7.Cql.CqlToElm;
using Hl7.Cql.CqlToElm.Toolkit;
using Hl7.Cql.CqlToElm.Toolkit.Extensions;
using Hl7.Cql.CodeGeneration.NET;
using Hl7.Cql.CodeGeneration.NET.Toolkit;
using Hl7.Cql.Invocation.Toolkit;
using Hl7.Cql.Invocation.Toolkit.Extensions;
using Hl7.Cql.Elm;
using Microsoft.Extensions.Logging;

new Program().PickExample(args.ElementAtOrDefault(0));

internal partial class Program
{
    void PickExample(string example)
    {
        switch (example)
        {
            case "210": LoadCqlFromDirSaveElmToDir(); break;
            case "220": LoadElmFromDirSaveCSharpAndDllToDir(); break;
            case "230": PackageCqlElmCSharpAndDllFromDirsSaveFhirResourcesToDir(); break;
            case "240": PackageViaCqlAndElmToolkitsSaveFhirResourcesToDir(); break;
            case "250": PackageViaCqlToolkitsSaveFhirResourcesToDir(); break;
            case "310": InvokingCqlHelloWorld(); break;
            case "320": InvokingCqlHelloWorldWithParameter(); break;
            case "330": InvokingCqlHelloWorldWithFunctionArgument(); break;
            // case "ExecuteBasicCqlHelloWorld":                               ExecuteBasicCqlHelloWorld(loggerFactory); break;
            // case "ExecuteBasicCqlHelloWorldWithDebugging":                  ExecuteBasicCqlHelloWorldWithDebugging(loggerFactory); break;
            // case "ElmExecuteCrossLibraryCalls":                             ElmExecuteCrossLibraryCalls(loggerFactory); break;
        }

        //ExecuteBasicCqlHelloWorld(loggerFactory);
        //ExecuteBasicCqlHelloWorldWithDebugging(loggerFactory);
        //ElmExecuteCrossLibraryCalls(loggerFactory);
    }

    private static void ExecuteBasicCqlHelloWorldWithDebugging(ILoggerFactory loggerFactory)
    {
        CqlToolkit cqlToolkit = new();

        using LibrarySetInvoker librarySetInvoker =
            cqlToolkit
                .AddCqlLibraries(
                    (CqlLibraryString)"""
                                      library ExecuteBasicCql version '1.0.0'

                                      define "HelloWorld" : 'CQL Says: "Hello, DevDays!"'
                                      """)
                .CreateLibrarySetInvoker(
                    elmToolkitConfig: new ElmToolkitConfig(
                        // In Visual Studio,
                        // - go to: Tools > Options > Debugging > Require source files to exactly match the original source code
                        // - uncheck the box
                        AssemblyCompilerDebugInformationFormat: AssemblyCompilerDebugInformationFormat.Embedded));

        CqlContext cqlContext = FhirCqlContext.WithDataSource();

        object? result = librarySetInvoker.InvokeLibraryDefinition(
            cqlContext: cqlContext,
            libraryIdentifier: (CqlVersionedLibraryIdentifier)"ExecuteBasicCql-1.0.0",
            definitionSignature: (DefinitionSignature)"HelloWorld");

        Console.WriteLine(result);
    }

    private static void ElmExecuteCrossLibraryCalls(ILoggerFactory loggerFactory)
    {
        // NOTICE: The CQL to ELM translation is not generating the correct ELM yet,
        // so for this demo, we'll use the ELM that is generated by Java tooling.
        /*
        CqlToolkit cqlToolkit = new(loggerFactory);
        cqlToolkit
            .AddCqlLibraries(
                // When copying code from any AI bot, be sure to remove zero-width spaces and tabs!
                (CqlLibraryString)"""
                                  library CommonFunctions version '1.0.0'

                                  define function IsAdult(ageInYears Integer):
                                    ageInYears >= 18

                                  define function CalculateAge(birthDate Date):
                                    difference in years between birthDate and Today()
                                  """,
                (CqlLibraryString)"""
                                  library PatientEligibility version '1.0.0'

                                  include CommonFunctions version '1.0.0'

                                  define function IsEligible(patientBirthDate Date):
                                    CommonFunctions.IsAdult(CommonFunctions.CalculateAge(patientBirthDate))
                                  """)
            .TranslateToElm();
            */

        ElmToolkit elmToolkit = new(
            loggerFactory,
            config: new ElmToolkitConfig(
                // In Visual Studio,
                // - go to: Tools > Options > Debugging > Require source files to exactly match the original source code
                // - uncheck the box
                AssemblyCompilerDebugInformationFormat: AssemblyCompilerDebugInformationFormat.Embedded));
        using LibrarySetInvoker librarySetInvoker =
            elmToolkit.AddElmLibraries(
                      [
                          Library.ParseFromJson(
                              """
                              {"library":{"annotation":[{"translatorVersion":"3.1.0","translatorOptions":"EnableLocators,EnableResultTypes","type":"CqlToElmInfo"}],"identifier":{"id":"CommonFunctions","version":"1.0.0"},"schemaIdentifier":{"id":"urn:hl7-org:elm","version":"r1"},"usings":{"def":[{"localIdentifier":"System","uri":"urn:hl7-org:elm-types:r1"}]},"statements":{"def":[{"locator":"3:1-4:18","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"IsAdult","context":"Patient","accessLevel":"Public","type":"FunctionDef","expression":{"locator":"4:3-4:18","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","type":"GreaterOrEqual","signature":[{"name":"{urn:hl7-org:elm-types:r1}Integer","type":"NamedTypeSpecifier"},{"name":"{urn:hl7-org:elm-types:r1}Integer","type":"NamedTypeSpecifier"}],"operand":[{"locator":"4:3-4:12","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"ageInYears","type":"OperandRef"},{"locator":"4:17-4:18","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","valueType":"{urn:hl7-org:elm-types:r1}Integer","value":"18","type":"Literal"}]},"operand":[{"name":"ageInYears","operandTypeSpecifier":{"locator":"3:36-3:42","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"{urn:hl7-org:elm-types:r1}Integer","type":"NamedTypeSpecifier"}}]},{"locator":"6:1-7:51","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"CalculateAge","context":"Patient","accessLevel":"Public","type":"FunctionDef","expression":{"locator":"7:3-7:51","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","precision":"Year","type":"DifferenceBetween","signature":[{"name":"{urn:hl7-org:elm-types:r1}Date","type":"NamedTypeSpecifier"},{"name":"{urn:hl7-org:elm-types:r1}Date","type":"NamedTypeSpecifier"}],"operand":[{"locator":"7:31-7:39","resultTypeName":"{urn:hl7-org:elm-types:r1}Date","name":"birthDate","type":"OperandRef"},{"locator":"7:45-7:51","resultTypeName":"{urn:hl7-org:elm-types:r1}Date","type":"Today"}]},"operand":[{"name":"birthDate","operandTypeSpecifier":{"locator":"6:40-6:43","resultTypeName":"{urn:hl7-org:elm-types:r1}Date","name":"{urn:hl7-org:elm-types:r1}Date","type":"NamedTypeSpecifier"}}]}]}}}
                              """),
                          Library.ParseFromJson(
                              """
                              {"library":{"annotation":[{"translatorVersion":"3.1.0","translatorOptions":"EnableLocators,EnableResultTypes","type":"CqlToElmInfo"}],"identifier":{"id":"PatientEligibility","version":"1.0.0"},"schemaIdentifier":{"id":"urn:hl7-org:elm","version":"r1"},"usings":{"def":[{"localIdentifier":"System","uri":"urn:hl7-org:elm-types:r1"}]},"includes":{"def":[{"locator":"3:1-3:39","localIdentifier":"CommonFunctions","path":"CommonFunctions","version":"1.0.0"}]},"statements":{"def":[{"locator":"5:1-6:73","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"IsEligible","context":"Patient","accessLevel":"Public","type":"FunctionDef","expression":{"locator":"6:3-6:73","resultTypeName":"{urn:hl7-org:elm-types:r1}Boolean","name":"IsAdult","libraryName":"CommonFunctions","type":"FunctionRef","signature":[{"name":"{urn:hl7-org:elm-types:r1}Integer","type":"NamedTypeSpecifier"}],"operand":[{"locator":"6:27-6:72","resultTypeName":"{urn:hl7-org:elm-types:r1}Integer","name":"CalculateAge","libraryName":"CommonFunctions","type":"FunctionRef","signature":[{"name":"{urn:hl7-org:elm-types:r1}Date","type":"NamedTypeSpecifier"}],"operand":[{"locator":"6:56-6:71","resultTypeName":"{urn:hl7-org:elm-types:r1}Date","name":"patientBirthDate","type":"OperandRef"}]}]},"operand":[{"name":"patientBirthDate","operandTypeSpecifier":{"locator":"5:45-5:48","resultTypeName":"{urn:hl7-org:elm-types:r1}Date","name":"{urn:hl7-org:elm-types:r1}Date","type":"NamedTypeSpecifier"}}]}]}}}
                              """)
                      ])
                      .CreateLibrarySetInvoker();

        CqlContext cqlContext = FhirCqlContext.WithDataSource();
        var libraryIdentifier = (CqlVersionedLibraryIdentifier)"PatientEligibility-1.0.0";
        var definitionSignature = new DefinitionSignature("IsEligible", [typeof(CqlDate)]);
        int yearsOld = 17;

        object?[] args =
        [
            new CqlDate(2025, 06, 10)
                .Add(new CqlQuantity(-yearsOld, "year"))
        ];
        object? result = librarySetInvoker.InvokeLibraryDefinition(
            cqlContext,
            libraryIdentifier,
            definitionSignature,
            args);
        Console.WriteLine($"Person of age {yearsOld} is {(result is not true ? "not " : "")}eligible.");
        Debug.Assert(result is true);

        yearsOld = 18;
        args =
        [
            new CqlDate(2025, 06, 10)
                .Add(new CqlQuantity(-yearsOld, "year"))
        ];
        result = librarySetInvoker.InvokeLibraryDefinition(
            cqlContext,
            libraryIdentifier,
            definitionSignature,
            args);
        Console.WriteLine($"Person of age {yearsOld} is {(result is not true ? "not " : "")}eligible.");
        Debug.Assert(result is false);
    }

    private static readonly string InitialCurrentDirectory = Environment.CurrentDirectory;
}