using Hl7.Cql.Runtime;

namespace Hl7.Cql.CqlToElm.Toolkit.Extensions;

/// <summary>
/// Provides extension methods for saving ELM files to a directory.
/// </summary>
public static partial class CqlToolkitExtensions
{
    /// <summary>
    /// Saves the ELM files generated by the CQL toolkit to the specified directory.
    /// </summary>
    /// <param name="cqlToolkit">The CQL toolkit instance.</param>
    /// <param name="directory">The directory to save the ELM files to.</param>
    /// <param name="writeIndented">Whether to write the JSON with indentation for readability. Default is <see langword="true"/>.</param>
    /// <param name="directoryPreparationStrategy">Optional strategy for preparing the directory. Default is to create the directory if it does not exist.</param>
    /// <returns>The CQL toolkit instance.</returns>
    public static CqlToolkit SaveElmFilesToDirectory(
        this CqlToolkit cqlToolkit,
        DirectoryInfo directory,
        bool writeIndented = true,
        DirectoryInfoHandler? directoryPreparationStrategy = null)
    {
        (directoryPreparationStrategy ?? DirectoryPreparationStrategy.CreateIfNotExists)(directory);

        var logger = cqlToolkit.CreateLogger();

        foreach (var (versionedLibraryIdentifier, _, elmLibrary) in cqlToolkit.GetCompletedCqlToElmTranslations())
        {
            var fileName = Path.Combine(directory.FullName, $"{versionedLibraryIdentifier}.json");
            File.WriteAllText(fileName, elmLibrary.SerializeToJson(writeIndented));
            logger.LogInformation("Saved ELM to file: {file}", fileName);
        }

        return cqlToolkit;
    }
}
