/*
 * Copyright (c) 2025, Firely, NCQA and contributors
 * See the file CONTRIBUTORS for details.
 *
 * This file is licensed under the BSD 3-Clause license
 * available at https://raw.githubusercontent.com/FirelyTeam/firely-cql-sdk/main/LICENSE
 */

using Hl7.Cql.Runtime;

namespace Hl7.Cql.CodeGeneration.NET.Toolkit;

/// <summary>
/// Represents the artifacts produced by the Elm Toolkit, including the input CQL library and optional result artifacts.
/// </summary>
/// <remarks>This type encapsulates the input CQL library and optionally the results generated by the Elm Toolkit.
/// Use the <see cref="WithResultArtifacts"/> method to create a new instance with updated result artifacts.</remarks>
/// <param name="InputElmLibrary"></param>
/// <param name="Results"></param>
public readonly record struct ElmToolkitArtifacts(
    ElmLibrary InputElmLibrary,
    ElmToolkitResultArtifacts? Results = null)
{
    /// <summary>
    /// The library identifier of the input CQL library.
    /// </summary>
    public CqlVersionedLibraryIdentifier LibraryIdentifier => InputElmLibrary.VersionedLibraryIdentifier;

    /// <summary>
    /// Creates a new instance of <see cref="ElmToolkitArtifacts"/> with the specified result artifacts.
    /// </summary>
    /// <param name="cSharpSourceCode">The C# source code associated with the result artifacts. This parameter cannot be null or empty.</param>
    /// <param name="assemblyBinary">The binary representation of the compiled assembly. This parameter can be null if no assembly binary is
    /// available.</param>
    /// <param name="debugSymbols">The debug symbols associated with the compiled assembly. This parameter can be null if no debug symbols are
    /// available.</param>
    /// <returns>A new <see cref="ElmToolkitArtifacts"/> instance containing the specified result artifacts.</returns>
    public ElmToolkitArtifacts WithResultArtifacts(
        string cSharpSourceCode,
        byte[]? assemblyBinary,
        byte[]? debugSymbols) => this with
    {
        Results = new ElmToolkitResultArtifacts(cSharpSourceCode, assemblyBinary, debugSymbols)
    };
}