using System.CodeDom.Compiler;
using Hl7.Cql.Abstractions;

namespace CqlSdkPrototype.Runtime.Invokers;


/// <summary>
/// Represents an invoker for a CQL library.
/// </summary>
public abstract class LibraryInvoker
{
    public abstract CqlVersionedLibraryIdentifier LibraryVersionedIdentifier { get; }

    public abstract IReadOnlyDictionary<string, LibraryDefinitionInvoker> Definitions { get; }

    public static bool TryCreateFromType(
        RuntimeApi runtimeApi,
        Type libraryType,
        [NotNullWhen(true)] out LibraryInvoker? libraryInvoker)
    {
        libraryInvoker = runtimeApi.AsExtensible().UseServices(t =>
        {
            var logger = t.logger;
            var runtimeApi = t.runtimeApi;
            if (libraryType.GetCustomAttribute<CqlLibraryAttribute>() is not { })
            {
                logger?.LogDebug(
                    "Type {type} is not a CQL library because it does not have a CqlLibraryAttribute.",
                    libraryType.FullName);
                return null;
            }

            // The current version is set in by 'VersionPrefix' in 'cql-sdk.props',
            // which is also used to generate the 'CqlLibraryAttribute' in the CQL library.
            if (libraryType.GetCustomAttribute<GeneratedCodeAttribute>() is not
                {
                    Tool: ".NET Code Generation",
                    Version: { } version
                }
                || !Version.TryParse(version, out var cqlToolVersion))
            {
                logger?.LogDebug(
                    "Skipping type {type} because it was not generated by the CQL tool .NET Code Generation",
                    libraryType.FullName);
                return null;
            }

            if (LibraryInvoker_2_0_8_0.SupportsVersion(cqlToolVersion))
            {
                if (LibraryInvoker_2_0_8_0.TryCreateFromType(runtimeApi, libraryType, out var libraryInvoker))
                    return libraryInvoker;
            }

            logger?.LogDebug(
                "Skipping type {type} because it was generated with an unsupported version {ver} of the CQL tool.",
                libraryType.FullName,
                cqlToolVersion);

            return null;
        });
        return libraryInvoker != null;
    }
}