using System.CodeDom.Compiler;
using CqlSdkPrototype.Infrastructure;
using CqlSdkPrototype.Invocation.Internal;
using Hl7.Cql.Abstractions;

namespace CqlSdkPrototype.Invocation;


/// <summary>
/// Abstract base class for invoking CQL libraries.
/// </summary>
public abstract class LibraryInvoker
{
    /// <summary>
    /// Gets the versioned identifier of the CQL library.
    /// </summary>
    public abstract CqlVersionedLibraryIdentifier LibraryVersionedIdentifier { get; }

    /// <summary>
    /// Gets the dictionary of definition invokers for the CQL library.
    /// </summary>
    public abstract IReadOnlyDictionary<string, DefinitionInvoker> Definitions { get; }

    /// <summary>
    /// Tries to create a <see cref="LibraryInvoker"/> instance from the specified type.
    /// </summary>
    /// <param name="librarySetInvokerBuilder">The builder for the library set invoker.</param>
    /// <param name="libraryType">The type of the library.</param>
    /// <param name="libraryInvoker">When this method returns, contains the created <see cref="LibraryInvoker"/> instance, if the creation succeeded; otherwise, <see langword="null"/>.</param>
    /// <returns><see langword="true"/> if the creation succeeded; otherwise, <see langword="false"/>.</returns>
    public static bool TryCreateFromType(
        LibrarySetInvokerBuilder librarySetInvokerBuilder,
        Type libraryType,
        [NotNullWhen(true)] out LibraryInvoker? libraryInvoker)
    {
        libraryInvoker = null;
        var logger = librarySetInvokerBuilder.LoggerFactory.CreateLogger<LibraryInvoker>();

        if (libraryType.GetCustomAttribute<CqlLibraryAttribute>() is not { })
        {
            logger?.LogDebug(
                "Type {type} is not a CQL library because it does not have a CqlLibraryAttribute.",
                libraryType.FullName);
            return false;
        }

        // The current version is set in by 'VersionPrefix' in 'cql-sdk.props',
        // which is also used to generate the 'CqlLibraryAttribute' in the CQL library.
        if (libraryType.GetCustomAttribute<GeneratedCodeAttribute>() is not
            {
                Tool: ".NET Code Generation",
                Version: { } version
            }
            || !Version.TryParse(version, out var cqlToolVersion))
        {
            logger?.LogDebug(
                "Skipping type {type} because it was not generated by the CQL tool .NET Code Generation",
                libraryType.FullName);
            return false;
        }

        if (LibraryInvoker_2_0_8_0.SupportsVersion(cqlToolVersion))
        {
            if (LibraryInvoker_2_0_8_0.TryCreate(librarySetInvokerBuilder, libraryType, out libraryInvoker))
                return true;
        }

        logger?.LogDebug(
            "Skipping type {type} because it was generated with an unsupported version {ver} of the CQL tool.",
            libraryType.FullName,
            cqlToolVersion);

        return false;
    }
}
